### PR TITLE
Fix invalid x-ndjson payload format

### PR DESCRIPTION
**Pull request by cosmo0920**
Fixes https://github.com/fluent-plugins-nursery/fluent-plugin-out-http/issues/55

### CODE REVIEW

**Comment by cosmo0920** [comment]
@leverich Could you try this patch?

**Comment by cosmo0920** [comment]
I've confirmed that `x-ndjson` wrong format is fixed.

**Comment by leverich** [comment]
Hi @cosmo0920, I have attempted to use the `bulk request` option in this plugin again. It appears that my original issue report may have been in error! I believe commit `48f59df` should be reverted.

I tried to use 1.3.2 with `bulk_request true`, and I ended up with POST payloads that looked like:

```
"{\"message\":\"abc\",\"path\":\"test.log\"}\n{\"message\":\"def\",\"path\":\"test.log\"}\n{\"message\":\"xyz\",\"path\":\"test.log\"}\n"
```

I reverted to 1.3.1, and I could no longer reproduce the issue where the records are emitted as Ruby hashes. Bulk requests are correctly delivered as newline-delimited JSON objects.

For completeness, this is the complete fluentd.conf that I am testing with:

```
<source>
  @type tail
  format none
  path test.log
  path_key path
  pos_file .test.log.pos
  tag test.test
</source>

<match test.*>
  @type http
  endpoint_url http://127.0.0.1:6060
  serializer json
  bulk_request true
  <buffer>
    flush_interval 1s
  </buffer>
</match>
```

In also am using a trivial Python3 HTTP server to receive and dump the payloads I am seeing:

```
#!/usr/bin/env python3

from http.server import HTTPServer, BaseHTTPRequestHandler
from io import BytesIO
import sys

class TestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b'OK.\n')

    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        body = self.rfile.read(content_length).decode('utf-8')
        body = body.strip()
        body = body + '\n'
        sys.stdout.write(body)
        sys.stdout.flush()
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b'OK.\n')

def run(server_class=HTTPServer, handler_class=BaseHTTPRequestHandler):
    server_address = ('', 6060)
    httpd = server_class(server_address, handler_class)
    httpd.serve_forever()

if __name__ == "__main__":
    run(handler_class=TestHandler)
```

I am creating bulk requests by invoking the following:

```
echo -e 'abc\ndef\nxyz' >> test.log
```

With version 1.3.2, the output of listen.py is:

```
"{\"message\":\"abc\",\"path\":\"test.log\"}\n{\"message\":\"def\",\"path\":\"test.log\"}\n{\"message\":\"xyz\",\"path\":\"test.log\"}\n"
127.0.0.1 - - [20/Oct/2019 10:38:01] "POST / HTTP/1.1" 200 -
```

With version 1.3.1, the output of listen.py is:

```
{"message":"abc","path":"/home/leverich/fluentd/test.log"}
{"message":"def","path":"/home/leverich/fluentd/test.log"}
{"message":"xyz","path":"/home/leverich/fluentd/test.log"}
127.0.0.1 - - [20/Oct/2019 10:27:00] "POST / HTTP/1.1" 200 -
```

Thus, I now believe x-ndjson previously worked as intended. I'm afraid I do not know how to reproduce the behavior I was seeing before, so my issue report was probably in error.

I would recommend reverting `48f59df`.

Sorry for the trouble!

**Comment by cosmo0920** [comment]
I've released 1.3.3 as a revert release.
Could you check it?

**Comment by leverich** [comment]
1.3.3 is working great with bulk_request=true. Thank you!

**Pull request merged**
