### PR TITLE
Added plain text transport capability & specify cacert file for ssl verify

### PR DESCRIPTION
**Pull request by komal-SkyNET**
Capability allows the plugin to pass through raw plain text content as HTTP body without any parsing or transformation issues.

### CODE REVIEW

**Comment by komal-SkyNET** [comment]
Also, added feature to specify the cacert_file to use for ssl.

**Comment by ento** [comment]
Sorry for the delay here - I’m hoping to review in the next few days.

Note: If anyone would be interested in taking over the gem/repo or getting added as a maintainer/contributor, it’d be much appreciated. I don’t use fluentd now and it’d be good if someone who’s up-to-date with the current best practices can be involved.

**Comment by komal-SkyNET** [comment]
Sure, thanks. Also, if you could help me understand advise why the http-rate-limiting tests fail only for MAC OS?

**Comment by ento** [comment]
This repo is now under the care of the @fluent-plugins-nursery organization and I hope/believe this PR will be given the love it deserves soon.

As for the rate-limiting test on macOS, I don't have a good guess other than maybe something to do with WEBrick. Swapping it out for thin or something might help.

**Comment by cosmo0920** [comment]
> Swapping it out for thin

I swapped it out for reducing weird failure on macOS.

**Comment by komal-SkyNET** [comment]
Thank you!

Regards,
Komal

**Comment by komal-SkyNET** [comment]
Hey, just wondering why I don't appear under contributors; I see these changes in master branch as well.

**Comment by cosmo0920** [comment]
Oh, I forgot to use [`Co-Authored-By: ~`](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors) signature to uplift commit.
Sorry for inconvenience about this....

**Pull request merged**
